name: test_shuffle

on:
  push:
    branches:
      - 'main'

jobs:

  build_test_shuffle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # TTK dependencies
        sudo apt install -y \
          g++ \
          meson

    - name: Build & test
      run: |
        mkdir build
        cd build
        meson ..
        ninja
        meson test --verbose
